CREATE TABLE booking_travel
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id         VARCHAR(50)                             NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    status             VARCHAR(100)                            NOT NULL,
    description        VARCHAR(300),
    delete             BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE,
    created_by         VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by         VARCHAR(30),
    version            BIGINT                                  NOT NULL,
    price_room_type_id BIGINT                                  NOT NULL,
    quantity           INTEGER                                 NOT NULL,
    CONSTRAINT pk_booking_travel PRIMARY KEY (id)
);

ALTER TABLE booking_travel
    ADD CONSTRAINT uc_booking_travel_booking UNIQUE (booking_id);
CREATE TABLE booking_travel
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_id         VARCHAR(50)                             NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    currency_id        BIGINT                                  NOT NULL,
    status             VARCHAR(100)                            NOT NULL,
    description        VARCHAR(300),
    delete             BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by         VARCHAR(30),
    version            BIGINT                                  NOT NULL,
    price_room_type_id BIGINT                                  NOT NULL,
    quantity           INTEGER                                 NOT NULL,
    CONSTRAINT pk_booking_travel PRIMARY KEY (id)
);

ALTER TABLE booking_travel
    ADD CONSTRAINT uc_booking_travel_booking UNIQUE (booking_id);