CREATE TABLE cities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete      BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by  VARCHAR(30),
    version     BIGINT                                  NOT NULL,
    city_name   VARCHAR(200)                            NOT NULL,
    image_url   VARCHAR(400),
    country_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

CREATE TABLE countries
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(300),
    delete       BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE,
    created_by   VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by   VARCHAR(30),
    version      BIGINT                                  NOT NULL,
    country_code VARCHAR(50)                             NOT NULL,
    country_name VARCHAR(200)                            NOT NULL,
    image_url    VARCHAR(400),
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

ALTER TABLE countries
    ADD CONSTRAINT uc_countries_country_code UNIQUE (country_code);

ALTER TABLE countries
    ADD CONSTRAINT uc_countries_country_name UNIQUE (country_name);

ALTER TABLE cities
    ADD CONSTRAINT FK_CITIES_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);