spring:
  application:
    name: booking-vacation-gateway
server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
          netflix:
            eureka: DEBUG
springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: location-service
        url: /location/v3/api-docs
      - name: facility-service
        url: /facility/v3/api-docs
      - name: stay-service
        url: /stay/v3/api-docs
      - name: user-service
        url: /user/v3/api-docs
    config-url: /v3/api-docs/swagger-config