CREATE TABLE bed_room_types
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(300),
    delete       BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE,
    created_by   VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by   VARCHAR(30),
    version      BIGINT                                  NOT NULL,
    room_type_id BIGINT                                  NOT NULL,
    type_bedroom VARCHAR(50)                             NOT NULL,
    quantity     INTEGER                                 NOT NULL,
    image_url    VARCHAR(500),
    CONSTRAINT pk_bed_room_types PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   VARCHAR(300),
    delete        BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE,
    created_by    VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by    VARCHAR(30),
    version       BIGINT                                  NOT NULL,
    category_code VARCHAR(50)                             NOT NULL,
    category_name VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE room_type_images
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(300),
    delete       BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE,
    created_by   VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by   VARCHAR(30),
    version      BIGINT                                  NOT NULL,
    room_type_id BIGINT                                  NOT NULL,
    image_url    VARCHAR(500),
    CONSTRAINT pk_room_type_images PRIMARY KEY (id)
);

CREATE TABLE room_type_properties
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(300),
    delete       BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE,
    created_by   VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by   VARCHAR(30),
    version      BIGINT                                  NOT NULL,
    room_type_id BIGINT                                  NOT NULL,
    property_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_room_type_properties PRIMARY KEY (id)
);

CREATE TABLE room_type_services
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(300),
    delete       BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE,
    created_by   VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by   VARCHAR(30),
    version      BIGINT                                  NOT NULL,
    room_type_id BIGINT                                  NOT NULL,
    service_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_room_type_services PRIMARY KEY (id)
);

CREATE TABLE room_types
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description    VARCHAR(300),
    delete         BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE,
    created_by     VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by     VARCHAR(30),
    version        BIGINT                                  NOT NULL,
    stay_id        BIGINT                                  NOT NULL,
    room_type_name VARCHAR(300)                            NOT NULL,
    size           DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_room_types PRIMARY KEY (id)
);

CREATE TABLE stay_facilities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete      BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by  VARCHAR(30),
    version     BIGINT                                  NOT NULL,
    stay_id     BIGINT                                  NOT NULL,
    facility_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_stay_facilities PRIMARY KEY (id)
);

CREATE TABLE stay_images
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete      BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by  VARCHAR(30),
    version     BIGINT                                  NOT NULL,
    stay_id     BIGINT                                  NOT NULL,
    image_url   VARCHAR(400)                            NOT NULL,
    "primary"   BOOLEAN     DEFAULT FALSE               NOT NULL,
    CONSTRAINT pk_stay_images PRIMARY KEY (id)
);

CREATE TABLE stay_rules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete      BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by  VARCHAR(30),
    version     BIGINT                                  NOT NULL,
    stay_id     BIGINT                                  NOT NULL,
    rule_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_stay_rules PRIMARY KEY (id)
);

CREATE TABLE stay_services
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete      BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by  VARCHAR(30),
    version     BIGINT                                  NOT NULL,
    stay_id     BIGINT                                  NOT NULL,
    service_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_stay_services PRIMARY KEY (id)
);

CREATE TABLE stays
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete      BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by  VARCHAR(30),
    version     BIGINT                                  NOT NULL,
    stay_code   VARCHAR(50)                             NOT NULL,
    stay_name   VARCHAR(200)                            NOT NULL,
    address     VARCHAR(400)                            NOT NULL,
    city_id     BIGINT                                  NOT NULL,
    category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_stays PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_category_code UNIQUE (category_code);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_category_name UNIQUE (category_name);

ALTER TABLE stay_images
    ADD CONSTRAINT uc_stay_images_image_url UNIQUE (image_url);

ALTER TABLE stays
    ADD CONSTRAINT uc_stays_stay_code UNIQUE (stay_code);

ALTER TABLE bed_room_types
    ADD CONSTRAINT FK_BED_ROOM_TYPES_ON_ROOM_TYPE FOREIGN KEY (room_type_id) REFERENCES room_types (id);

ALTER TABLE room_types
    ADD CONSTRAINT FK_ROOM_TYPES_ON_STAY FOREIGN KEY (stay_id) REFERENCES stays (id);

ALTER TABLE room_type_images
    ADD CONSTRAINT FK_ROOM_TYPE_IMAGES_ON_ROOM_TYPE FOREIGN KEY (room_type_id) REFERENCES room_types (id);

ALTER TABLE room_type_properties
    ADD CONSTRAINT FK_ROOM_TYPE_PROPERTIES_ON_ROOM_TYPE FOREIGN KEY (room_type_id) REFERENCES room_types (id);

ALTER TABLE room_type_services
    ADD CONSTRAINT FK_ROOM_TYPE_SERVICES_ON_ROOM_TYPE FOREIGN KEY (room_type_id) REFERENCES room_types (id);

ALTER TABLE stays
    ADD CONSTRAINT FK_STAYS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE stay_facilities
    ADD CONSTRAINT FK_STAY_FACILITIES_ON_STAY FOREIGN KEY (stay_id) REFERENCES stays (id);

ALTER TABLE stay_images
    ADD CONSTRAINT FK_STAY_IMAGES_ON_STAY FOREIGN KEY (stay_id) REFERENCES stays (id);

ALTER TABLE stay_rules
    ADD CONSTRAINT FK_STAY_RULES_ON_STAY FOREIGN KEY (stay_id) REFERENCES stays (id);

ALTER TABLE stay_services
    ADD CONSTRAINT FK_STAY_SERVICES_ON_STAY FOREIGN KEY (stay_id) REFERENCES stays (id);