CREATE TABLE facilities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   VARCHAR(300),
    delete        BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE,
    created_by    VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by    VARCHAR(30),
    version       BIGINT                                  NOT NULL,
    facility_code VARCHAR(50)                             NOT NULL,
    facility_name VARCHAR(200)                            NOT NULL,
    image_url     VARCHAR(500),
    CONSTRAINT pk_facilities PRIMARY KEY (id)
);

CREATE TABLE properties
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   VARCHAR(300),
    delete        BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE,
    created_by    VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by    VARCHAR(30),
    version       BIGINT                                  NOT NULL,
    property_name VARCHAR(200)                            NOT NULL,
    image_url     VARCHAR(500),
    CONSTRAINT pk_properties PRIMARY KEY (id)
);

CREATE TABLE rules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete      BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by  VARCHAR(30),
    version     BIGINT                                  NOT NULL,
    rule_code   VARCHAR(50)                             NOT NULL,
    rule_name   VARCHAR(300)                            NOT NULL,
    image_url   VARCHAR(400),
    CONSTRAINT pk_rules PRIMARY KEY (id)
);

CREATE TABLE services
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(300),
    delete       BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE,
    created_by   VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by   VARCHAR(30),
    version      BIGINT                                  NOT NULL,
    service_code VARCHAR(50)                             NOT NULL,
    service_type VARCHAR(200)                            NOT NULL,
    service_name VARCHAR(200)                            NOT NULL,
    image_url    VARCHAR(500),
    CONSTRAINT pk_services PRIMARY KEY (id)
);

ALTER TABLE facilities
    ADD CONSTRAINT uc_facilities_facility_code UNIQUE (facility_code);

ALTER TABLE facilities
    ADD CONSTRAINT uc_facilities_facility_name UNIQUE (facility_name);

ALTER TABLE properties
    ADD CONSTRAINT uc_properties_property_name UNIQUE (property_name);

ALTER TABLE rules
    ADD CONSTRAINT uc_rules_rule_code UNIQUE (rule_code);

ALTER TABLE rules
    ADD CONSTRAINT uc_rules_rule_name UNIQUE (rule_name);

ALTER TABLE services
    ADD CONSTRAINT uc_services_service_code UNIQUE (service_code);

ALTER TABLE services
    ADD CONSTRAINT uc_services_service_name UNIQUE (service_name);