CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(300),
    delete       BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE,
    created_by   VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by   VARCHAR(30),
    version      BIGINT                                  NOT NULL,
    user_id      VARCHAR(50)                             NOT NULL,
    first_name   VARCHAR(100)                            NOT NULL,
    last_name    VARCHAR(100)                            NOT NULL,
    sex          BOOLEAN                                 NOT NULL,
    birth_date   date                                    NOT NULL,
    phone_number VARCHAR(30)                             NOT NULL,
    address      VARCHAR(400),
    avatar       VARCHAR(500),
    username     VARCHAR(100)                            NOT NULL,
    email        VARCHAR(200)                            NOT NULL,
    password     VARCHAR(200)                            NOT NULL,
    role         VARCHAR(100)                            NOT NULL,
    blocking     BOOLEAN     DEFAULT FALSE               NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);