CREATE TABLE emotions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(300),
    delete       BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE,
    created_by   VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by   VARCHAR(30),
    version      BIGINT                                  NOT NULL,
    emotion_name VARCHAR(100)                            NOT NULL,
    image_url    VARCHAR(500)                            NOT NULL,
    CONSTRAINT pk_emotions PRIMARY KEY (id)
);

CREATE TABLE review_emotions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description    VARCHAR(300),
    delete         BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE,
    created_by     VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by     VARCHAR(30),
    version        BIGINT                                  NOT NULL,
    review_stay_id BIGINT                                  NOT NULL,
    emotion_id     BIGINT                                  NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_review_emotions PRIMARY KEY (id)
);

CREATE TABLE review_stays
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                VARCHAR(200)                            NOT NULL,
    review_good          TEXT        DEFAULT ''                  NOT NULL,
    review_bad           TEXT        DEFAULT ''                  NOT NULL,
    rating               INTEGER                                 NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    booking_id           BIGINT                                  NOT NULL,
    description          VARCHAR(300),
    delete               BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE,
    created_by           VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by           VARCHAR(30),
    version              BIGINT                                  NOT NULL,
    stay_id              BIGINT                                  NOT NULL,
    staff_score          INTEGER                                 NOT NULL,
    facilities_score     INTEGER                                 NOT NULL,
    cleanliness_score    INTEGER                                 NOT NULL,
    comfort_score        INTEGER                                 NOT NULL,
    value_of_money_score INTEGER                                 NOT NULL,
    location_score       INTEGER                                 NOT NULL,
    wifi_score           INTEGER                                 NOT NULL,
    CONSTRAINT pk_review_stays PRIMARY KEY (id)
);

ALTER TABLE emotions
    ADD CONSTRAINT uc_emotions_emotion_name UNIQUE (emotion_name);

ALTER TABLE review_emotions
    ADD CONSTRAINT FK_REVIEW_EMOTIONS_ON_EMOTION FOREIGN KEY (emotion_id) REFERENCES emotions (id);

ALTER TABLE review_emotions
    ADD CONSTRAINT FK_REVIEW_EMOTIONS_ON_REVIEW_STAY FOREIGN KEY (review_stay_id) REFERENCES review_stays (id);