CREATE TABLE coupons
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete      BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by  VARCHAR(30),
    version     BIGINT                                  NOT NULL,
    coupon_code VARCHAR(50)                             NOT NULL,
    coupon_name VARCHAR(200)                            NOT NULL,
    start_date  date                                    NOT NULL,
    end_date    date                                    NOT NULL,
    CONSTRAINT pk_coupons PRIMARY KEY (id)
);

CREATE TABLE currencies
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description     VARCHAR(300),
    delete          BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE,
    created_by      VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by      VARCHAR(30),
    version         BIGINT                                  NOT NULL,
    country_id      BIGINT                                  NOT NULL,
    currency_code   VARCHAR(50)                             NOT NULL,
    currency_name   VARCHAR(200)                            NOT NULL,
    currency_symbol VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_currencies PRIMARY KEY (id)
);

CREATE TABLE discounts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete      BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by  VARCHAR(30),
    version     BIGINT                                  NOT NULL,
    percent     DOUBLE PRECISION                        NOT NULL,
    start_date  date                                    NOT NULL,
    end_date    date                                    NOT NULL,
    CONSTRAINT pk_discounts PRIMARY KEY (id)
);

CREATE TABLE price_room_type
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description      VARCHAR(300),
    delete           BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE,
    created_by       VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by       VARCHAR(30),
    version          BIGINT                                  NOT NULL,
    room_type_id     BIGINT                                  NOT NULL,
    tax_id           BIGINT                                  NOT NULL,
    value            DECIMAL                                 NOT NULL,
    discount_id      BIGINT                                  NOT NULL,
    price_breakfast  DECIMAL                                 NOT NULL,
    allow_refundable BOOLEAN     DEFAULT FALSE               NOT NULL,
    need_credit_card BOOLEAN     DEFAULT FALSE               NOT NULL,
    CONSTRAINT pk_price_room_type PRIMARY KEY (id)
);

CREATE TABLE taxes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(300),
    delete      BOOLEAN     DEFAULT FALSE               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE,
    created_by  VARCHAR(50) DEFAULT 'SYSTEM'            NOT NULL,
    updated_by  VARCHAR(30),
    version     BIGINT                                  NOT NULL,
    precent     DOUBLE PRECISION,
    CONSTRAINT pk_taxes PRIMARY KEY (id)
);

ALTER TABLE coupons
    ADD CONSTRAINT uc_coupons_coupon_code UNIQUE (coupon_code);

ALTER TABLE coupons
    ADD CONSTRAINT uc_coupons_coupon_name UNIQUE (coupon_name);

ALTER TABLE currencies
    ADD CONSTRAINT uc_currencies_currency_code UNIQUE (currency_code);

ALTER TABLE currencies
    ADD CONSTRAINT uc_currencies_currency_name UNIQUE (currency_name);

ALTER TABLE currencies
    ADD CONSTRAINT uc_currencies_currency_symbol UNIQUE (currency_symbol);

ALTER TABLE price_room_type
    ADD CONSTRAINT FK_PRICE_ROOM_TYPE_ON_DISCOUNT FOREIGN KEY (discount_id) REFERENCES discounts (id);

ALTER TABLE price_room_type
    ADD CONSTRAINT FK_PRICE_ROOM_TYPE_ON_TAX FOREIGN KEY (tax_id) REFERENCES taxes (id);